const tongueTwisters = [
  `Als Anna abends aß, aß Anna abends Ananas.`,
  `Als wir noch in der Wiege lagen gab's noch keine Liegewaagen. Jetzt kann man in den Waagen liegen und sich in allen Lagen wiegen.`,
  `Am Ammersee aßen achtzig Afrikaner alle Abend appetitliche Ananas.`,
  `Amerikaner kamen nach Kamenz um Carmen zu umarmen.`,
  `Auf dem Rasen rasen Hasen, atmen rasselnd durch die Nasen.`,
  `Auf den sieben Robbenklippen sitzen sieben Robbensippen, die sich in die Rippen stippen, bis sie von den Klippen kippen.`,
  `Zwei Astronauten kauten und kauten während sie blaugrüne Mondsteine klaubten.`,
  `Herr von Hagen darf ich's wagen, sie zu fragen, welchen Kragen sie getragen, als sie lagen krank am Magen in der Stadt zu Kopenhagen.`,
  `Lang schwang der Klang am Hang entlang.`,
  `Brautkleid bleibt Brautkleid und Blaukraut bleibt Blaukraut.`,
  `Bierbrauer Bauer braut braunes Bier, braunes Bier braut Bierbrauer Bauer.`,
  `Bernd Bolls, bürgerlicher Brauhausbesitzer bei Brauner, berühmte bayrische Bierhymne beginnt: "Biedere, brave Bierbrauerburschen bereiten beständig bitteres, braunes, bayrisches Bier.`,
  `Bürsten mit schwarzen Borsten bürsten besser als Bürsten mit blauen Borsten.`,
  `Die Bürsten mit den schwarzen Borsten bürsten besser, als die Bürsten mit den weißen Borsten bürsten.`,
  `Eine Diplombibliothekarin ist Bibliothekarin mit Diplom, eine Bibliothekarin mit Diplom ist eine Diplombibliothekarin.`,
  `Wenn der Benz bremst, brennt das Benzbremslicht.`,
  `Der bullige Bär in Birnen beißt, der bärtige Bauer Bernhard heißt.`,
  `Chinesisches Schüsselchen, chinesisches Schüsselchen, chinesisches Schüsselchen.`,
  `Denke nie du denkst, denn wenn du denkst, du denkst, dann denkst du nicht, dann denkst du nur du denkst, denn das Denken der Gedanken ist gedankenloses Denken.`,
  `Denke nie gedacht zu haben, denn das Denken der Gedanken ist gedankenloses Denken.`,
  `Denen Dänen, denen Dänen Dänen dehnen, dehnen deren Dänen.`,
  `Der Mondschein schien schon schön.`,
  `Weißt du das, dass das "das" das meistgebrauchte Wort im Satz ist?`,
  `Drei dicke dumme Damen donnern durch das dicke doofe Dorf.`,
  `Ein Dutzend nuschelnde Dutzer dutzen nuschelnd dutzende dutzender Nuschler nuschelnd.`,
  `Wenn dein Dackel zu mein Dackel noch mal Dackel sagt, kriegt dein Dackel von mein Dackel so eine gedackelt, dass dein Dackel nicht mehr "Dackel" sagen kann.`,
  `Einsame Esel essen nasse Nesseln gern, nasse Nesseln essen einsame Esel gern.`,
  `Esel essen Nesseln gern, Nesseln essen Esel gern.`,
  `Das Weinfass, das Frau Weber leerte, verheerte ihre Leberwerte.`,
  `Der Frosterfrosch frostet im Froschfroster, frostet der Frosterfrosch im Froschfroster?`,
  `Fischers Fritze fischt frische Fische;Frische Fische fischt Fischers Fritze.`,
  `Flöte mit flötenden Flößern fahren den fließenden Fluss herab.`,
  `Früh fressen freche Frösche Früchte. Freche Frösche fressen früh Früchte.`,
  `Fips mixt Fixmixdrinks, fix mixt Fips Fixmixdrinks`,
  `Fischer, die als Floßfahrer auf Flussflößen auf Floßflüssen fahren, sind fischende Floßflussflussfloßfahrer.`,
  `Fromme Frösche fressen frische Frühlingszwiebeln, aber freche Frösche fressen frische Früchte.`,
  `Fischers frisch frisierter Fritze frisst frisch frittierte Frisch-Fisch-Frikadellen.`,
  `Flankenkicker Flick kickt flinke Flanken. Flinke Flanken kickt Flankenkicker Flick.`,
  `Frische Kirschen knirschen nicht. Nicht knirschen frische Kirschen.`,
  `Der froschforschende Froschforscher forscht in der froschforschenden Froschforschung.`,
  `Wenn Fliegen hinter Fliegen fliegen, fliegen Fliegen Fliegen nach.`,
  `Furcht vor Fruchtfleisch führt zu Flucht vor Fruchtfleisch.`,
  `Vier fünfmal vervierfacht macht mehr als fünf viermal verfünffacht.`,
  `Griesbrei bleibt Griesbrei und Kriegsbeil bleibt Kriegsbeil.`,
  `Wenn hinter Griechen Griechen kriechen, kriechen Griechen Griechen nach.`,
  `Wenn Grillen Grillen grillen, grillen Grillen Grillen!`,
  `Der Kaplan Klapp plant ein klappbares Pappplakat.`,
  `Die Katze tritt die Treppe krumm. Der Kater tritt sie gerade.`,
  `Der Krabbenfischer knabbert Knabberkrabben, Knabberkrabben knabbert der Krabbenfischer.`,
  `Die Katze tritt die Treppe krumm, die Katze tritt die Treppe krumm.`,
  `Ein knallroter Krebs aus der Krummen Lanke kroch bequem über eine kalte kühle Korbflasche.`,
  `Es klapperte die Klapperschlang', bis ihre Klapper schlapper klang.`,
  `Ein krummer Krebs kroch über eine krumme Schraube.`,
  `Kalle Kahlekatzenglatzenkratzer kratzt kahle Katzenglatzen.`,
  `Klaus Knopf liebt Knödel, Klöße, Klöpse. Knödel, Klöße, Klöpse liebt Klaus Knopf.`,
  `Klitzekleine Kinder können keinen Kirschkern knacken!`,
  `Kleine Kinder können keinen Kaffee kochen. Keinen Kaffee können kleine Kinder kochen.`,
  `Kluge kleine Kinder kaufen keine kleinen Kleiderknöpfe.`,
  `Kostbarer Kownoer Käse kostet Kulacken keinen Kopeken.`,
  `Kleine Katzen und kleine Kinder kugeln gern mit Kugeln und Klinkern.`,
  `Kleine Nussknacker knacken knackig. Knackiger knacken große Nussknacker.`,
  `Klitzekleine Katzen kotzen klitzekleine Kotze. Klitzekleine Kotze kotzen klitzekleine Katzen.`,
  `Kannst du denn dem kleinen konstantinopolitanischen Dudelsackpfeifer pfeifen?`,
  `Kreischende Krähen knabbern im kalten Winter Kerne und Körner.`,
  `Der Krabbenfischer knabbert Knabberkrabben, Knabberkrabben knabbert der Krabbenfischer.`,
  `Hans hackt Holz hinterm Haus.`,
  `Hans hört hinterm Holzhaus Hubert Hansen heiser husten.`,
  `Franken ist da, wo Hasen "Hosen" und Hosen "Husen" heißen.`,
  `Der Leutnant von Leuthen befahl seinen Leuten, nicht eher zu läuten als der Leutnant von Leuthen seinen Leuten das Läuten befahl.`,
  `Lang schwang der Klang den Hang entlang.`,
  `Montags macht mir meine muntere Mutter mittags meistens Mus.`,
  `Mama mag morgens meistens Milch mit Marmelade mampfen.`,
  `Mischwasserfischer heißen Mischwasserfischer, weil sie im Mischwasser Mischwasserfische fischen.`,
  `Max macht Wachsmaskenwachs, Wachsmaskenwachs macht Max.`,
  `Missi und Sippi schippern über'n miesen Mississippi.`,
  `Mondschein schien schon schön, schön schien schon Mondschein.`,
  `Es soll vorkommen, daß die Nachkommen mit dem Einkommen nicht mehr auskommen und dann vollkommen verkommen umkommen.`,
  `Hat die Maus die Mandeln und das Marzipan gemaust?`,
  `Gibst Du dem Opi Opium, bringt Opium den Opi um.`,
  `Der Pralli prallt die Ralle bis die Schnalle knallt, bis die Schnalle knallt prallt der Pralli die Ralle.`,
  `Im Potsdamer Boxclub boxt der Potsdamer Postbusboss.`,
  `Auf den sieben Robbenklippen sitzen sieben Robbensippen, die sich in die Rippen stippen, bis sie von den Klippen kippen.`,
  `Der Flugplatzspatz nahm auf dem Flugplatz Platz. Auf dem Flugplatz nahm der Flugplatzspatz Platz.`,
  `Plättbrett bleibt Plättbrett`,
  `Rasent rasantes Rumpelstielschen ruppelt Rolos rauf und runter.`,
  `Reitende Kosaken mit rotem Krummsäbeln reiten mit kräftigen Rössern den Arratberg hinauf.`,
  `Russische Russen rutschen russische Rutschen russisch runter.`,
  `Der Sumpfschlump schlumpft sich durch den Sumpfschlumpf.`,
  `Siebzehn Schnitzer, die auf siebzehn Schnitzsitzen sitzen und mit ihren spitzen Schnitzern Ritzen in ihr Schnitzholz schlitzen, wobei sie schwitzen, sind siebzehn schwitzende, schnitzende, auf dem Schnitzsitz sitzende, spitze Schnitzer benützende Schnitzholzritzenschlitzer.`,
  `Sona seift alle seriösen Senioren ein, alle seriösen Senioren seift Sona ein.`,
  `Esel essen Nesseln nicht. Nesseln essen Esel nicht!`,
  `Das Schleimschwein schleimt schweinisch im Schleim, im Schleim schleimt schweinisch das Schleimschwein.`,
  `In einem Schokoladenladen laden Ladenmädchen Schokolade aus. Ladenmädchen laden Schokolade in einem Schokoladenladen aus.`,
  `Schnecken erschrecken wenn sie an Schnecken schlecken denn zum Schrecken vieler Schnecken manche Schnecken, Schnecken nicht schmecken.`,
  `Schneiders Schere schneidet scharf. Scharf schneidet Schneiders Schere.`,
  `Manches Schminkschwämmchen schwimmt und manches Schminkschwämmchen schwimmt nicht.`,
  `Sechzig tschechische Chefchemiker scheuchen keusche chinesische Mönche in seichte Löschteiche.`,
  `Spinnende spanische Spanner verspannen spannende spanische Spinner.`,
  `Ein sehr schwer sehr schnell zu sprechender Spruch ist ein Schnellsprechspruch.`,
  `Schmalspurbahnschienen sind schmaler als Breitspurbahnschienen.`,
  `Ein Stachelschwein, ein Stachelschwein, das muss ein Schwein mit Stacheln sein, doch hat es keine Stachelein, so ist es auch kein Stachelschwein.`,
  `Schnecken erschrecken, wenn sie an Schnecken schlecken, weil zum Schrecken vieler Schnecken, Schnecken nicht schmecken.`,
  `Sensitive Selektionssimulatoren sondieren sogar sekundär-strukturierte Sonarselektoren - sogar sekundär-strukturierte Sonarselektoren sondieren sensitive Selektionssimulatoren.`,
  `Sieben Schneeschipper schippen sieben Schippen Schnee.`,
  `Sieben Schneeschaufler schaufeln sieben Schaufeln Schnee.`,
  `Tschechische Regisseure schätzen schöne chinesische Schüsselchen.`,
  `Der Streusalzstreuer zahlt keine Streusalzstreuersteuer, keine Streusalzstreuersteuer zahlt der Streusalzstreuer.`,
  `Testtexte texten Testtexter, Testtexter texten Testtexte.`,
  `Sie war die teigigste Teigmuschel unter allen teigigen Teigmuscheln des Muschelteichs.`,
  `Glücklich ist der Tourist, wenn er auf einer Tour ist und in einer Tour isst.`,
  `In Ulm und um Ulm und um Ulm herum. In Ulm, um Ulm und um Ulm herum.`,
  `Auf des Fleischhauers Schild war der Abstand zwischen "Käse" und "und" und "und" und "Wurst" zu klein geraten.`,
  `Wenn um Rumkugeln Rumkugeln herumkugeln, kugeln um Rumkugeln Rumkugeln herum.`,
  `Wenn der Benz bremst, brennt das Benz-Bremmslicht.`,
  `Wenn Fliegen hinter Fliegen fliegen, dann fliegen Fliegen Fliegen nach.`,
  `Wer nichts weiß und weiß, dass er nichts weiß, weiß mehr als der, der nichts weiß und nicht weiß, dass er nichts weiß.`,
  `Wenn Klappergras blüht, bleibt Klappergras immer noch grün.`,
  `Wer wer weiß was weiß, weiß wer weiß wie viel.`,
  `Ein weißer Whiskeymixer mixt weißen Whiskey. Weißen Whiskey mixt ein weißer Whiskeymixer.`,
  `Der Whiskeymixer mixt Whisky wunderbar.`,
  `Wir Wiener Wäscheweiber würden weiße Wäsche waschen, wenn wir wüssten, wo warmes, weiches Wasser wäre.`,
  `Vor Weihnachten wirbeln wunderschöne weiße Schneeflocken wie weiche wollige Watte über den Waldrand hinweg.`,
  `Max wachst Wachsmasken. Was wachst Max? Wachsmasken wachst Max.`,
  `Der Wachsmaskenmacher macht Wachsmasken aus Wachsmaskenwachs.`,
  `Zehn zahme Ziegen zogen zehn Zentner Zucker zum Zoo.`,
  `Zwanzig Zwerge zeigen Handstand, zehn im Wandschrank, zehn am Sandstrand.`,
  `Zwischen zwei Zwetschgenzweigen sitzen zwei zechenschwarze tschechisch zwitschernde Zwergschwalben.`,
  `Zwischen zwei Zwetschgenzweigen zwitschern zwei zwitschernde Schwalben.`,
  `Es lagen zwei zischende Schlangen zwischen zwei spitzen Steinen und zischten dazwischen.`,
  `Der Braumeister zu Zipf zapft zehn Fässer Zipfer.`,
  `Der Zweck hat den Zweck den Zweck zu bezwecken; wenn der Zweck seinen Zweck nicht bezweckt, hat der Zweck keinen Zweck!`,
  `Der Zahnarzt zieht Zähne mit Zahnarztzange im Zahnarztzimmer.`,
  `Geschwisterzwist zwischen Slivovic schlürfenden, spitzen, twistenden und schwitzenden Zwitscherschwestern.`,
  `Zehn Ziegen ziehen zehn Zentner Zement zum Zahnarzt zum Zementieren zerbrochener Zähne.`,
  `Zwei Ziegen zogen zum Zoo.`,
  `Zwüsche zwei Zwetschgezwieg zwitschere zwei Schwalbe.`,
  `Katzen schmatzen, putzen sich mit ihren Tatzen, hassen alles was sie verpatzen.`,
];

module.exports = tongueTwisters;
